account/urls.py
from django.urls import path, include
from account import views
from appoint_app.views import dashboard, home, terms
from django.contrib.auth import views as auth_views


urlpatterns = [

    path('toggle-dark-mode/', views.toggle_dark_mode, name='toggle_dark_mode'),
    path("video-call-patient/", views.video_call_patient, name='video-call-patient'),
    
    # ---------- Register \ LogIN \Logout \ delet \UPDAYTEuser-------------#

    path("login/", views.login_user, name='login'),
    path("logout/", views.logout_user, name='logout'),
    path("log/", views.admin_otp_verification, name='admin_otp_verification'),
    path("reg/", views.reg_otp_verification, name='reg_otp_verification'),


    path('register-patient/', views.register_patient, name='register-patient'),
    path("update-profile/<str:username>/", views.update_profile, name='update-profile'),


    path('delete_account_confirmation/', views.delete_account_confirmation, name='delete_account_confirmation'),
    path('password-change/', auth_views.PasswordChangeView.as_view(), name='password_change'),
   

# ------------  Land Portal --------------
    path('patients-portal/',dashboard , name='patients_portal'),
    path('admins-portal/', dashboard, name='admins_portal'),


# -----------View/manage Appointments --------------------
    path("view-appointments/", views.view_appointments, name='view-appointments'),
    path("view-appointments-manage/", views.view_appointments_manage, name='view-appointments-manage'),
    path("view-appointment/<str:appointment_id>/", views.view_appointment, name='view-appointment'),
    path("appointments-list/", views.all_appointments, name='appointments-list'),
    
    

    

    #path("approved-appointments/", views.approved_appointments, name='approved-appointments'),
    #path("view-all-appointments/", views.view_all_appointments, name='view-all-appointments'),

    #path("view-appointment-patient/<str:appointment_id>/", views.view_appointment_patient, name='view-appointment-patient'),

    #path("close-appointment/<str:appointment_id>/", views.close_appointment, name='close-appointment'),
    #path("closed-appointments/", views.closed_appointments, name='closed-appointments'),
    path("cancel-appointment/<str:appointment_id>/", views.cancel_appointment, name='cancel-appointment'),
    path("delete-appointment/<str:appointment_id>/", views.delete_appointment, name='delete-appointment'),




# --------------------- Create Appointmet /SLOT ----------------------

    path("create-appointment-patient/", views.create_appointment_patient, name='create-appointment-patient'),


    path("book_slot_patient/", views.book_slot_patient, name='book-slot-patient'),
    path("create_auto_slot/",views.create_auto_slot,name='create-auto-slot'),


# ----------- PDFs ----------------------


    path('account/export_appointment_pdf/<str:appointment_id>/', views.export_appointment_pdf, name='export_appointment_pdf'),
    path('export/appointments_payments/pdf/', views.export_appointments_payments_pdf, name='export_appointments_payments_pdf'),
    path('export_user_payments_pdf/', views.export_user_payments_pdf, name='export_user_payments_pdf'),
    path('export_admin_all_payments_pdf/', views.export_admin_all_payments_pdf, name='export_admin_all_payments_pdf'),
     

   
    

   
   



# ---------------------- Payments --------------
  

    path("all-payments/", views.view_payments_patient, name='all-payments'),


    path("manage-user-payments/", views.all_payments, name='manage-user-payments'),

    
# ****************************************
    path("", include('django.contrib.auth.urls')),
]

appoint/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [

    
    path("__reload__/", include("django_browser_reload.urls")),
    path('admin/', admin.site.urls),
    path("", include('appoint_app.urls')),
  
    path("accounts/", include('account.urls')),
    path('payments/', include('payments.urls')),

  #  path('password-change/', auth_views.PasswordChangeView.as_view(), name='password_change'),
   # path('password-change/done/', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),
    
  #  path('check_email_exists/', views.check_email_exists, name='check_email_exists'),
   # path('password-reset/', auth_views.PasswordResetView.as_view(template_name='appoint_app/password_reset_form.html'), name='password_reset'),
   # path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='appoint_app/password_reset_done.html'), name='password_reset_done'), 
   # path('password-reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='appoint_app/password_reset_confirm.html'), name='password_reset_confirm'),
   # path('password-reset/complete/', auth_views.PasswordResetCompleteView.as_view(template_name='appoint_app/password_reset_complete.html'), name='password_reset_complete'),


]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.STATIC_ROOT)

appoint_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
  
    path("", views.dashboard, name='dashboard'),
    path("home/", views.home, name='home'),
    path('terms/', views.terms, name='terms'),
    path('about/', views.about, name='about'),

    
    path('admin/logout/', views.logout_view, name='logout'),
     
    
]

account/forms.py
from datetime import time
from django import forms
from .models import User
from appoint_app.models import generate_appointment_id, Misc,Appointment
from django.utils import timezone
from django.utils.translation import gettext_lazy as _
from django.contrib.auth.forms import UserCreationForm
from django.forms.widgets import PasswordInput
from django.utils.safestring import mark_safe
from phonenumber_field.formfields import PhoneNumberField

from django.core.exceptions import ValidationError
from django.http import HttpResponse

GENDER_CHOICES = [
        ('Male', 'Male'),
        ('Female', 'Female'),
        ('Other', 'Other')
    ]
    
RESOLVED_CHOICES = [
    (True, 'Yes'),
    (False, 'No'),
]

DAY_CHOICES = [
    ('Monday', 'Monday'),
    ('Tuesday', 'Tuesday'),
    ('Wednesday', 'Wednesday'),
    ('Thursday', 'Thursday'),
    ('Friday', 'Friday'),
    ('Saturday', 'Saturday'),
    ('Sunday', 'Sunday'),
    ]






# Create a custom password input widget with an eye icon to toggle password visibility
class PasswordInputWithToggle(PasswordInput):
    def render(self, name, value, attrs=None, renderer=None):
        rendered = super().render(name, value, attrs, renderer)
        eye_toggle = '''
        <div class="relative">
            {}
            <div class="absolute inset-y-0 right-0 pr-3 flex items-center text-sm leading-5">
                <button 
                    type="button" 
                    class="text-blue-500 hover:text-gray-700 focus:outline-none focus:shadow-outline-blue active:text-gray-800 toggle-password">
                    <i class="fas fa-eye"></i>
                </button>
            </div>
        </div>
        '''.format(rendered)
        return mark_safe(eye_toggle)




# Create a custom Patient registration form
class PatientRegistrationForm(UserCreationForm):
   # patient_type = forms.ChoiceField(required=True, label='Patient Type', choices=PATIENT_TYPE_CHOICES, widget=forms.Select(attrs={'id': 'patient_type', 'required': True, 'class': 'block w-full rounded-full border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6'}),)
  #  patient_id = forms.CharField(label='Patient ID', required=True, widget=forms.TextInput(attrs={'id': 'patient_id', 'autocomplete': '', 'placeholder': 'Enter your ID', 'required': True, 'class': 'block w-full rounded-full border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6'}), max_length=15)
    
    phone_number = PhoneNumberField(required=True, widget=forms.NumberInput(attrs={'class': 'block w-full rounded-full border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6', 'id': 'phone_number','value':'+91 ', 'autocomplete': 'tel', 'placeholder': 'Enter your Phone Number'}))

    email = forms.EmailField(required=True, widget=forms.EmailInput(attrs={'class': 'block w-full rounded-full border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6', 'id': 'email', 'autocomplete': 'email', 'placeholder': 'Enter your Email'}))
    username = forms.CharField(label='Username', widget=forms.TextInput(attrs={'id': 'username', 'placeholder': 'Create your unique username', 'required': True, 'class': 'block w-full rounded-full border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6'}), required=True)
    password1 = forms.CharField(required=True, label='Password', widget=PasswordInputWithToggle(attrs={'id': 'password', 'autocomplete': 'current-password', 'placeholder': 'Create your password', 'required': True, 'class': 'block w-full rounded-full border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6 pr-10'}))
    password2 = forms.CharField(required=True, label='Confirm Password', widget=PasswordInputWithToggle(attrs={'id': 'password2', 'autocomplete': 'new-password', 'placeholder': 'Confirm your password', 'required': True, 'class': 'block w-full rounded-full border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6 pr-10'}))
    
    agree_to_terms = forms.BooleanField(
        label='Agree to Terms of Use & Privacy',
        required=True,
        widget=forms.CheckboxInput(attrs={
            'id': 'agree_to_terms',
            'class': 'form-checkbox text-red h-9 w-9',
        }),
    )
    
    # Meta class to define the model and fields to be used in the form
    class Meta:
        model = User
        fields = ['username', 'email', 'phone_number',  'password1', 'password2', 'agree_to_terms']
    

 
    


    
 
    



# Create a custom form to update Profile (by Patients)
class UpdateProfileForm(forms.ModelForm):   
    profile_photo = forms.ImageField(label='', required=False, widget=forms.ClearableFileInput(attrs={
        'class': 'hidden', 'accept': 'image/*',
        'id': 'profile_photo',
        'class': 'block w-full mt-2 mb-2 rounded-full border-0 border-none p-2 text-gray-900 placeholder-gray-400 focus:outline-none focus:ring-2 focus:ring-indigo-600 focus:border-transparent sm:text-sm'
    }))   
    first_name = forms.CharField(label='First Name:', required=True, widget=forms.TextInput(attrs={'id': 'first_name', 'autocomplete': '', 'placeholder': 'Enter your first name', 'required': True, 'class': 'block w-full rounded-full border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6'}), max_length=50)
    last_name = forms.CharField(label='Last Name:', required=True, widget=forms.TextInput(attrs={'id': 'last_name', 'autocomplete': '', 'placeholder': 'Enter your last name', 'required': True, 'class': 'block w-full rounded-full border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6'}), max_length=50)
    phone_number = PhoneNumberField(required=True, widget=forms.NumberInput(attrs={'class': 'block w-full rounded-full border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6', 'id': 'phone_number','value':'+91 ', 'autocomplete': 'tel', 'placeholder': 'Enter your Phone Number'}))
    email = forms.EmailField(required=True, label='Email:', widget=forms.EmailInput(attrs={'class': 'block w-full rounded-full border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6', 'id': 'email', 'autocomplete': 'email', 'placeholder': 'Update your Email'}))
    username = forms.CharField(label='Username:', widget=forms.TextInput(attrs={'id': 'username', 'placeholder': 'Create your unique username', 'required': True, 'class': 'block w-full rounded-full border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6'}), required=True)
    
    class Meta:
        model = User
        fields = ['profile_photo','username', 'first_name', 'last_name', 'email', 'phone_number']




class Create_auto_slot(forms.ModelForm):  
    from_date = forms.DateField()
    to_date = forms.DateField()
    
    class Meta:
        model = Misc
        fields = [ 'from_date','to_date']

templates/appoint_app/admin_otp_verification.html
{% if request.user.is_authenticated %}
{% load static %}
{% load crispy_forms_tags %}
<!DOCTYPE html>
<html>
<head>
    <style>
        body {
            padding-top: 7em;
        }

        /* Style for OTP input fields */
        .otp-input {
            width: 30px;
            height: 30px;
            margin: 0 5px;
            font-size: 18px;
            text-align: center;
        }
    </style>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'appoint_app/css/messages.css' %}">
    <title>Akankha Homeo | OTP Verification</title>
</head>
<body style="background-color: #f2f2f5;">
    <div class="container">
        <!-- Display error messages -->
        <div class="message-container">
            {% if messages %}
            {% for message in messages %}
            <div class="message {% if message.tags == 'success' %}message-success{% elif message.tags == 'error' %}message-error{% endif %}">
                {{ message }}
            </div>
            {% endfor %}
            {% endif %}
        </div>
        <div class="text-center pb-2">
            <img src="{% static 'appoint_app/images/appoint-master-logo.png' %}" alt="Logo" style="width: 43px; height: 43px;">
        </div>
        <h4 class="text-center mb-4" style="color: rgba(12, 189, 21, 0.932);">OTP Verification</h4>
        <form id="otpForm" action="." method="POST" class="mx-auto" style="max-width: 400px;">
            {% csrf_token %}
            <div class="form-row justify-content-center">
                <label for="otp">Enter the OTP sent to <b>{{user.email}}☑️</b>:</label>
            </div>
            
            <div class="form-row justify-content-center mb-3 mt-3">
                <!-- Create 6 input fields for OTP -->
                <input type="text" class="otp-input" maxlength="1" name="digit1" required>
                <input type="text" class="otp-input" maxlength="1" name="digit2" required>
                <input type="text" class="otp-input" maxlength="1" name="digit3" required>
                <input type="text" class="otp-input" maxlength="1" name="digit4" required>
                <input type="text" class="otp-input" maxlength="1" name="digit5" required>
                <input type="text" class="otp-input" maxlength="1" name="digit6" required>
            </div>
        </form>
        
        <p class="mt-4 text-center text-sm text-gray-500">
            Back to
            <a href="{% url 'login' %}" style="text-decoration: none; color: rgb(55, 16, 194); font-weight: 600;">Login</a>
        </p>  
    </div>

    <!-- JavaScript for automatically moving cursor to next field and verifying OTP -->
    <script>
        document.addEventListener('DOMContentLoaded', function() {
            var otpFields = document.getElementsByClassName('otp-input');
            var currentIndex = 0;
    
            // Set focus on the first OTP field
            otpFields[currentIndex].focus();
    
            for (var i = 0; i < otpFields.length; i++) {
                otpFields[i].addEventListener('input', function() {
                    if (this.value.length == this.maxLength) {
                        // Move to the next OTP field
                        currentIndex = Array.prototype.indexOf.call(otpFields, this);
                        if (currentIndex < otpFields.length - 1) {
                            otpFields[currentIndex + 1].focus();
                        } else {
                            // Last field, submit form
                            document.getElementById('otpForm').submit();
                        }
                    } else if (this.value.length == 0) {
                        // Move to the previous OTP field if current field is cleared
                        currentIndex = Array.prototype.indexOf.call(otpFields, this);
                        if (currentIndex > 0) {
                            otpFields[currentIndex - 1].focus();
                        }
                    }
                });
            }
    
            // Allow using < and > keys to move left and right between input fields (Does not work!)
            document.addEventListener('keydown', function(e) {
                if (e.key === '<' || e.key === ',') {
                    e.preventDefault();
                    currentIndex = Math.max(0, currentIndex - 1);
                    otpFields[currentIndex].focus();
                } else if (e.key === '>' || e.key === '.') {
                    e.preventDefault();
                    currentIndex = Math.min(otpFields.length - 1, currentIndex + 1);
                    otpFields[currentIndex].focus();
                }
            });
    
            // Prevent form submission when pressing Enter key (Automatic otp submission)
            document.getElementById('otpForm').addEventListener('keypress', function(e) {
                if (e.key === 'Enter') {
                    e.preventDefault();
                }
            });
        });
    </script>
     
    <script src="{% static 'appoint_app/js/login_patient.js' %}"></script>
</body>
</html>

{% endif %}

templates/appoint_app/appointments_payments_report.html
<!DOCTYPE html>
{% load static %}
{% load tz %}
<html>
<head>
    <style>
        table {
            width: 100%;
            border-collapse: collapse;
        }
        th, td {
            border: 1px solid black;
            padding: 5px;
        }
        .center-content {
            display: flex;
            justify-content: center;
            align-items: center;
        }
    </style>
    <script defer src="{% static 'appoint_app/js/date_time.js' %}"></script>
</head>
<body>
    <section class="center-content bg-primary p-1 mb-2 text-white rounded">
    <div class="logo">
        <img src="static/appoint_app/images/appoint-master-logo.png" width="37" height="37" alt="Logo">
    </div>
    <div>
        <h6 style="font-size: 14.6px">All Appointments</h6>
    </div>
    <div style="margin-bottom: 4px;">
        <span id="real-time-clock" style="font-weight: 700; font-size: 14.4px;">
            {% localtime on %}
                {% now "l, F j, Y H:i:s" %}
            {% endlocaltime %}
        </span>
    </div>
    </section>
    <table>
        <tr style="width: 100%;">
            <th>Appointment ID</th>
            <th>Area</th>
            <th>Appointee</th>
            <th>Type</th>
            <th>Appointed Doctor</th>
            <th>Booked</th>
            <th>Approved</th>
            <th>Scheduled</th>
            <th>Closed</th>
            <th>Appointment Status</th>
            <th>Payment Status</th>
        </tr>
        {% for row in data %}
        <tr>
            {% for cell in row %}
            <td>{{ cell }}</td>
            {% endfor %}
        </tr>
        {% endfor %}
    </table>
    <style>
        footer {
            font-size: 13px;
            display: flex;
            justify-content: center;
            align-items: center;
        }
    </style>
    <footer class="container-fluid bg-primary fixed-bottom text-white text-bold">
        <img src="static/appoint_app/images/appoint-master-logo.png" width="20" height="20" alt="Logo"> ©
        2025 Akankha Homeo Research Centre
    </footer>
</body>
</html>

templates/appoint_app/cancel_appointment.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Cancel Confirmation@Admin</title>
    <style>
        body {
            display: flex;
            justify-content: center;
            align-items: center;
            height: 80vh;
            margin: 0;
            background-color: #f0f0f0;
        }
        .container {
            text-align: center;
            padding: 30px;
            background-color: #fff;
            border-radius: 8px;
            box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
        }
        .btn-delete {
            background-color: #e53e3e;
            color: #fff;
            border: none;
            padding: 10px 15px;
            margin-right: 10px;
            border-radius: 9px;
            cursor: pointer;
            margin-bottom: 5px;
        }
        .btn-delete:hover {
            background-color: #c53030;
        }
        .btn-cancel {
            background-color: #3182ce;
            color: #fff;
            border: none;
            padding: 10px 15px;
            border-radius: 9px;
            cursor: pointer;
            margin-bottom: 5px;
        }
        .btn-cancel:hover {
            background-color: #2c5282;
        }
    </style>
	<link rel="stylesheet" href="{% static 'appoint_app/css/messages.css' %}">
</head>
<body>
    <div class="container">
        <div class="text-center pb-2">
            <img src="{% static 'appoint_app/images/appoint-master-logo.png' %}" alt="Logo" style="width: 43px; height: 43px;">
        </div>
        <h2 style="font-size: 21px; font-family:'Times New Roman', Times, serif;">Confirm Appointment Cancel</h2>
        <p>Are you sure you want to cancel the appointment?</p>
        <form method="post">
            {% csrf_token %}
            <button type="submit" class="btn-delete" style="text-decoration: none;">Yes</button>
            <a href="/" class="btn-cancel" style="text-decoration: none;">No</a>
        </form>
    </div>
</body>
</html>

templates/appoint_app/update_profile.html
{% if request.user.is_authenticated%}
{% load static tailwind_tags %}
<!DOCTYPE html>
<html class="h-full bg-violet-50" lang="en">
	<head>
        <title>Akankha Homeo | Update Profile@Patient</title>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <meta http-equiv="X-UA-Compatible" content="ie=edge">
            <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" />
            <link rel="stylesheet" href="{% static 'appoint_app/css/messages.css' %}">
        {% tailwind_css %}
	</head>
	<body>
		<div class="flex min-h-full flex-col justify-center px-10 py-10 lg:px-8">
            <div class="message-container">
				{% if messages %}
				{% for message in messages %}
				<div class="message {% if message.tags == 'success' %}message-success{% elif message.tags == 'error' %}message-error{% endif %}">
					{{ message }}
				</div>
				{% endfor %}
				{% endif %}
			</div>	
			<div class="sm:mx-auto sm:w-full sm:max-w-sm">
			  <img class="mx-auto h-10 top-1 w-auto" src="{% static 'appoint_app/images/appoint-master-logo.png' %}" alt="Logo">
			  <h2 class="mt-2 text-center text-2xl font-bold leading-9 tracking-tight text-blue-800">Update Profile</h2>
			</div>
		<!--	<p class="mt-4 text-center text-sm text-gray-500">
				<a href=""  class="text-red-500 text-md mt-1 font-bold">Update NEXT OF KIN</a>
			</p>-->
		  
			<div class="update-profile-form-patient sm:mx-auto sm:w-full sm:max-w-sm">
				<form action="{% url 'update-profile' username=profile.username %}" method="POST" enctype="multipart/form-data">
					{% csrf_token %}
					{% for field in form %}
					<div>
						<label class="form-label">{{ field.label }}</label>
						{% if field.name == 'dob' %}
						<input type="date" name="{{ field.name }}" id="{{ field.id }}" value="{{ profile.dob|date:'Y-m-d' }}" class="block w-full rounded-full border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6">
						{% elif field.name == 'profile_photo' %}
						<div class="flex flex-col items-center mt-2 justify-center relative">
							{% if profile.profile_photo %}
							<img src="{{ profile.profile_photo.url }}" alt="+" class="w-24 h-24 rounded-full mt-2 cursor-pointer bg-violet-100" onclick="choosePhoto()">
							{% else %}
							<label for="id_profile_photo" class="w-full rounded-full border-1 border-none cursor-pointer flex  items-center justify-center font-semibold text-red-700">Choose Photo</label>
							{% endif %}
							<input type="file" id="id_profile_photo" name="profile_photo" accept="image/*" class="hidden" onchange="showPreview(this)">
						</div>
						{% else %}
						{{ field }}
						{% endif %}
						{% if field.errors %}
						<div class="text-red-500 text-sm mt-1 font-semibold">
							{% for error in field.errors %}
							{{ error }}
							{% endfor %}
						</div>
						{% endif %}
					</div>
					{% endfor %}
					  
					<div class="mt-5 flex justify-center">
						<button type="submit" class="relative w-full border-0 py-1.5 items-center justify-center bg-gradient-to-r from-purple-500 to-blue-500 hover:from-purple-600 hover:to-blue-600 focus:outline-none focus:ring focus:ring-purple-300 active:bg-blue-700 rounded-full text-white font-semibold shadow-md transition duration-300 ease-in-out transform hover:scale-105">Update Profile</button>
					</div>
				</form>
				<p class="mt-4 text-center text-sm text-gray-500">
					Back to
					<a href="/" style="text-decoration: none; color: rgb(74, 17, 206); font-weight: 600;">Dashboard</a>
				</p>  
			</div>	
		</div>
		<script src="{% static 'appoint_app/js/profile_photo.js' %}"></script>
		<script src="{% static 'appoint_app/js/register_patient.js' %}"></script>
	</body>
</html>
{% endif %}